name: Frontend Deploy

on:
  push:
    branches: 
      - main
    paths:
      - 'front/**'
  pull_request:
    branches: 
      - develop
    paths:
      - 'front/**'
      - .github/workflows/deploy.yml
      
env:
  working-directory: ./front
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ${{ env.working-directory }}

      - name: Run build
        run: yarn run build
        env: 
            CI: "" 
        working-directory: ${{ env.working-directory }}
        
      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ap-northeast-2
          
      - name: Upload to S3
        run: aws s3 cp --recursive --region ap-northeast-2 build
            s3://pick-place
        working-directory: ${{ env.working-directory }}
